### ISSUE TITLE
Salesforce is not defined 

### ISSUE THREAD

**Issue by sibanand-cis** [Krisa/meteor-accounts-salesforce#2]
I am working with Meteor 0.8.3

When I am trying to click the Configure Salesforce:

```
Uncaught ReferenceError: Salesforce is not defined salesforce_client.js:3
Meteor.loginWithSalesforce salesforce_client.js:3
Template._loginButtonsLoggedOutSingleLoginButton.events.click .login-button login_buttons_single.js:33
(anonymous function) templating.js:83
(anonymous function) view.js:542
Blaze.withCurrentView view.js:375
(anonymous function) view.js:541
(anonymous function) events.js:47
jQuery.event.dispatch jquery.js:4624
elemData.handle jquery.js:4292

```

Can you please verify and let me know what I am missing here.

**Comment by Krisa** [comment]
Sorry for the (very) late answer. The package was totally outdated, hence the error you had... 

I have just pushed a new version, this time on atmosphere which is compatible with the latest version of Meteor. There is also an example which shows how that works. Let me know if you have any issue. I will close the issue in the meantime.
